### ISSUE TITLE
Add envsubst pkg

### ISSUE THREAD

**Issue by chrisdostert** [opspec-pkgs/project#74]
## User story
**As** a consumer of opspec pkgs
**I want** an envsubst pkg
**In order to** perform posix style env var substitution on text

## Notes
example
```yaml
inputs:
  vars:
    object:
      description: vars to replace in the form of a name/value map. see [example](/example-vars.json)"
  template:
    string:
      description: template referencing vars in shell format: `$var` `${var}`
outputs:
  result:
    string:
      description: hydrated template w/ all vars replaced
```
